### ISSUE TITLE
it gives error

### ISSUE THREAD

**Issue by Vikas5686** [Hackertrackersj/Tbomb#11]

**Comment by Vikas5686** [comment]
wait please
   Subscribe Nitro Hacker Youtube Channel
TBomb.sh: line 122: cd: Tbomb: No such file or directory
python3: can't open file '/root/bomber.py': [Errno 2] No such file or directory
                                                                                                                                       
┌──(kali㉿windows)-[~/Tbomb]
└─$ python3 bomber.py                                                                                                              2 ⨯
Traceback (most recent call last):
  File "/home/kali/Tbomb/bomber.py", line 19, in <module>
    from utils.decorators import MessageDecorator
  File "/home/kali/Tbomb/utils/decorators.py", line 1, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
                                                                                                                                       
┌──(kali㉿windows)-[~/Tbomb]
└─$                                                                                                                                1 ⨯

**Comment by Hackertrackersj** [comment]
PYTHON2 BOBMBER.PY

**Comment by 0n1cOn3** [comment]
The original TBomb (https://github.com/TheSpeedX/TBomb) has no such missbehaviour. I recommend to use the official TBomb release which has a active Telegram Support. 

@Hackertrackersj bomber.py is written in python3.... not in python2 *FACEPALM*
